swagger: "2.0"
info:
  title: beego Test API
  description: beego has a very cool tools to autogenerate documents for your API
  version: 1.0.0
  termsOfService: http://beego.me/
  contact:
    email: astaxie@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /v1
paths:
  /user/:
    get:
      tags:
      - user
      description: get all users
      operationId: UserController.GetAllUser
    post:
      tags:
      - user
      description: add a new user
      operationId: UserController.Add User
      parameters:
      - in: body
        name: RealName
        description: "true"
        schema:
          type: string
        type: string
      - in: body
        name: Email
        description: "true"
        schema:
          type: string
        type: string
      - in: body
        name: RealName
        description: "true"
        schema:
          type: string
        type: string
      - in: body
        name: UserPassword
        description: "true"
        schema:
          type: string
        type: string
      responses:
        "201":
          description: ""
          schema:
            $ref: '#/definitions/services.UserService.User'
        "400":
          description: ""
    delete:
      tags:
      - user
      parameters:
      - in: query
        name: userID
        description: required
        type: integer
        format: int64
definitions:
  services.UserService.User:
    title: User
    type: object
tags:
- name: user
  description: |
    UserController struct
    Operations for User
